services:
  - type: web
    name: llm-server
    env: docker
    dockerfilePath: ./llm-server/Dockerfile
    dockerContext: ./llm-server
    envVars:
      - key: PORT
        value: "8002"
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: shared_data
      mountPath: /app/shared_data
    healthCheckPath: /
    numInstances: 1

  - type: worker
    name: celery-worker
    env: docker
    dockerfilePath: ./llm-server/worker.Dockerfile
    dockerContext: ./llm-server
    disk:
      name: shared_data
      mountPath: /app/shared_data
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
    startCommand: celery -A celery_app worker --loglevel=info

  - type: web
    name: dashboard
    env: docker
    dockerfilePath: ./dashboard/Dockerfile
    dockerContext: ./dashboard
    disk:
      name: shared_data
      mountPath: /app/shared_data
    envVars:
      - key: PORT
        value: "8000"

databases:
  - name: mysql
    databaseName: opencopilot
    user: dbuser
    plan: standard

  - name: redis
    ipAllowList: []

  - name: qdrant
    plan: standard

envVarGroups:
  - name: llm-server-config
    envVars:
      - key: MYSQL_URL
        value: ${MYSQL_URL}
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: QDRANT_URL
        value: ${QDRANT_URL}
      - key: OPENAI_API_KEY
        sync: false